### ISSUE TITLE
2D Art Concept Weapons

### ISSUE THREAD

**Issue by Adicus-Alexander** [GAME-2332/argame#11]
Create concept art for player weapons. Include a top-down view and at least one other angle for each design. Each design should be able to be connected to or placed on top of a tower. 
Player weapons include:
-	A gun for the player character 
-       A sniper rifle
-	A sentry turret
-	A sniper’s nest
-	A rocket launcher

**Comment by AoTora98** [comment]
![Sentry Gun Tower](https://user-images.githubusercontent.com/112512808/197013121-06e31dc1-79aa-4735-aaaf-de1b6dfd7fb2.png)
![Rocket Launcher Mobile](https://user-images.githubusercontent.com/112512808/197013128-4fbf81c6-7cf4-4bf5-b4f6-570c12d31557.png)
![Rocket Launcher Turret](https://user-images.githubusercontent.com/112512808/197013129-bb0ead05-3299-477d-9f41-272ef582b3bc.png)

**Comment by Adicus-Alexander** [comment]
Looks good 👍🏾

**Comment by professaurChris** [comment]
Please use these as a reference guide for your art. 

![Image](https://user-images.githubusercontent.com/46843521/197836810-197e8206-263f-41e0-abab-d7dadda174d9.png)


![Image](https://user-images.githubusercontent.com/46843521/197837067-f971530a-6750-4ad6-af37-89b72a0e5861.png)

**Comment by BecBrock** [comment]
![Image](https://user-images.githubusercontent.com/112132801/199130128-7126e667-23b3-410a-b7a4-42150e393c75.png)
![Image](https://user-images.githubusercontent.com/112132801/199130129-bdb4354e-71c2-479f-a686-494b0c61d4b5.png)

**Comment by BecBrock** [comment]
Added pictures here by accident.

**Comment by professaurChris** [comment]
Need an update on concepts for these.

**Comment by AoTora98** [comment]
![Sniper Nest](https://user-images.githubusercontent.com/112512808/199664483-d8d2c37d-8fbb-4718-8bd2-cc47e7229c10.png)
![Sentry Turret 02](https://user-images.githubusercontent.com/112512808/199664484-d93c592a-380e-46d4-9685-4963f961ae2f.png)
![Sentry Turret](https://user-images.githubusercontent.com/112512808/199664487-a6eba1eb-c478-4b4f-9268-ad38135e44fe.png)
![Assault Rifle](https://user-images.githubusercontent.com/112512808/199664745-31feec71-7bef-4de7-85e1-37b07b89480d.png)
![Sniper Rifle](https://user-images.githubusercontent.com/112512808/199664747-847ac6d9-246b-47b2-8f3c-c1d7070de786.png)
