### ISSUE TITLE
3D Art Map Tile

### ISSUE THREAD

**Issue by Adicus-Alexander** [GAME-2332/argame#13]
Create a map tile that measures 1 unit in Unity. This tile will be used as a base for map terrain as well as distributed to 3D modelers in order to help maintain scale during the creation of assets.

**Comment by professaurChris** [comment]
Waiting on this.

**Comment by BecBrock** [comment]
I just sent measurement guide cubes to Adicus. I can't upload right now because I don't have the second project on my desktop.

**Comment by BecBrock** [comment]
[GuideCubes.zip](https://github.com/GAME-2332/argame/files/9865038/GuideCubes.zip)
