### ISSUE TITLE
Levels Tutorial & 1 Sketches

### ISSUE THREAD

**Issue by HschwandtHCC** [GAME-2332/argame#14]
Create 2 top view level sketches for the levels shown above. Use the grid Nehal shared in the discord to draw it out. 1 unit being a placeable defense item. Use green for the soldier in the center, red for the path enemy units will take to the soldier, and blue for the squares that the player can place a defense item. Keep it simple and clean and design with the difficulty of the assigned level in mind. The goal is to have 14 levels that flow well together and are ready for greyboxing.

**Comment by SBM382** [comment]
![Tutorial_Skecth](https://user-images.githubusercontent.com/70292179/196846288-a429be91-1a04-4daf-9e39-34a8a156d463.jpg)
![Level1](https://user-images.githubusercontent.com/70292179/196846290-2d2137c7-8ef1-4e12-8e84-18160feee4b7.jpg)

**Comment by SBM382** [comment]
![Tutorial_Skecth](https://user-images.githubusercontent.com/70292179/197018212-4a929ac5-391c-4283-9b95-57fc6dc481d2.jpg)
![Level1](https://user-images.githubusercontent.com/70292179/197018219-ba8b142e-645c-4dfd-bfa2-6be111f6ac4e.jpg)
I updated the map to the new measurements
