### ISSUE TITLE
Core health + damage mechanics

### ISSUE THREAD

**Issue by aeonic-dev** [GAME-2332/argame#23]
Enemy health, damage, player health, and enemies reducing player health on collision (and also instantly dying I guess).

**Comment by awetos** [comment]
Enemy Health:
- Create UI Health Bar that faces camera
- Health updates when damage is taken

Animation:
- Show text of damage taken or given

Functions: 
TakeDamage: Enemy receives damage from the player and reduces its own health
GiveDamage: Enemy deals damage to the player / soldier character
Spawn: Get all references, start walking.
OnCollisionEnter: If it collides with a player character, start trading damage. If the other collider is a projectile from a player turret, start taking damage.

**Comment by awetos** [comment]
Enemy Health:
- Create UI Health Bar that faces camera
- Health updates when damage is taken

Animation:
- Show text of damage taken or given

Functions: 
TakeDamage: Enemy receives damage from the player and reduces its own health
GiveDamage: Enemy deals damage to the player / soldier character
Spawn: Get all references, start walking.
OnCollisionEnter: If it collides with a player character, start trading damage. If the other collider is a projectile from a player turret, start taking damage.
