### ISSUE TITLE
Brent 3D Props

### ISSUE THREAD

**Issue by HschwandtHCC** [GAME-2332/argame#29]
Create two tents and a bush following the instructions left by the art department

- Use Maya and Adobe Substance Painter 3D
- Must be modern military style. If you need examples there is a docx file that adicus sent to the art section in the class discord.
- Keep poly count 1,000 or less.
- Follow scale provided by art team
- Must be textured using the tutorial left by the artist department.
- If assigned multiple props of the same object, they must be variations.
- Provide first prop to Adicus for testing

**Comment by NekotTheBrave** [comment]
![Image](https://user-images.githubusercontent.com/67830152/199789155-552afe82-317f-4114-985d-bbbff69f37c8.png)

**Comment by NekotTheBrave** [comment]
![Image](https://user-images.githubusercontent.com/67830152/202572959-0c1e76aa-65d7-468e-b7f5-749a60a165f3.png)
