### ISSUE TITLE
Fernando 3D Props

### ISSUE THREAD

**Issue by HschwandtHCC** [GAME-2332/argame#30]
Create a barricade, storage container, rock pile following the instructions left by the art department

- Use Maya and Adobe Substance Painter 3D
- Must be modern military style. If you need examples there is a docx file that adicus sent to the art section in the class discord.
- Keep poly count 1,000 or less.
- Follow scale provided by art team
- Must be textured using the tutorial left by the artist department.
- If assigned multiple props of the same object, they must be variations.
- Provide first prop to Adicus for testing

**Comment by Daemoncel** [comment]
![image](https://user-images.githubusercontent.com/112131230/198372338-4358900c-bc68-4908-acf4-4f98b3b68335.png)

**Comment by Daemoncel** [comment]
LOW POLY Storage Container 
![image](https://user-images.githubusercontent.com/112131230/199783843-aa84b0c6-cac3-442a-9ec4-139089faf2a2.png)
High Poly 
![image](https://user-images.githubusercontent.com/112131230/199783999-04b41f63-9180-4d42-a323-efb55f7b3d21.png)
