### ISSUE TITLE
Silvano 3D Props

### ISSUE THREAD

**Issue by HschwandtHCC** [GAME-2332/argame#31]
Create a bush, storage container, sandbag following the instructions left by the art department

Use Maya and Adobe Substance Painter 3D
Must be modern military style. If you need examples there is a docx file that adicus sent to the art section in the class discord.
Keep poly count 1,000 or less.
Follow scale provided by art team
Must be textured using the tutorial left by the artist department.
If assigned multiple props of the same object, they must be variations.
Provide first prop to Adicus for testing

**Comment by professaurChris** [comment]
Adding to this list, create four different variations of grass "planes" for the environment.

**Comment by SBM382** [comment]
![Bush](https://user-images.githubusercontent.com/70292179/199788198-d2425579-98e9-476d-8ebb-28018c8f27a6.jpg)
![Grass_Variations](https://user-images.githubusercontent.com/70292179/199788200-82fd6aa4-d9a6-4408-87b0-d3acbcf05de8.jpg)

**Comment by SBM382** [comment]
![Container](https://user-images.githubusercontent.com/70292179/202051037-3c90af12-a755-4634-86d4-0c8324ec7769.jpg)
![SandBag](https://user-images.githubusercontent.com/70292179/202051041-4cadc6e7-0986-49c1-beba-8d978e56c189.jpg)
