### ISSUE TITLE
Nehal 3D Props

### ISSUE THREAD

**Issue by HschwandtHCC** [GAME-2332/argame#33]
Create a chainlink fence, sandbag, barrier following the instructions left by the art department

Use Maya and Adobe Substance Painter 3D
Must be modern military style. If you need examples there is a docx file that adicus sent to the art section in the class discord.
Keep poly count 1,000 or less.
Follow scale provided by art team
Must be textured using the tutorial left by the artist department.
If assigned multiple props of the same object, they must be variations.
Provide first prop to Adicus for testing

**Comment by NehalHaider** [comment]
![Image](https://user-images.githubusercontent.com/112117655/200659842-2e70f10a-86c5-46a9-8271-f388480d539c.png)

**Comment by NehalHaider** [comment]
![Image](https://user-images.githubusercontent.com/112117655/200659979-a33d7491-e67b-4935-80be-712efca086a0.png)

**Comment by NehalHaider** [comment]
![Image](https://user-images.githubusercontent.com/112117655/200660115-e8358288-04f2-425a-b08a-5ba77527f371.png)

**Comment by NehalHaider** [comment]
![Image](https://user-images.githubusercontent.com/112117655/200667305-63519f73-d3e6-4049-a730-6093eb413320.png)
