### ISSUE TITLE
3D Model - Sentry Tower

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/argame#35]
With the same platform, create the upper body of the turret. Reference to Steven's concept art. Keep towers under 1000 poly.

**Comment by BecBrock** [comment]
![Image](https://user-images.githubusercontent.com/112132801/201225341-a271b06f-4d15-47ac-aff5-8fd8d5853ddb.png)



![Image](https://user-images.githubusercontent.com/112132801/201225362-13b4f570-32b2-4870-ac33-a78911bc3dd2.png)

**Comment by BecBrock** [comment]
![Image](https://user-images.githubusercontent.com/112132801/201243036-7060546a-09f0-41b0-8280-7669e16ff8a1.png)



![Image](https://user-images.githubusercontent.com/112132801/201243073-6e7c432f-c3c2-47f6-8fd3-019b61e7382b.png)



![Image](https://user-images.githubusercontent.com/112132801/201243086-079eef03-5dc0-4311-b6eb-a1269c9d9ae3.png)
