### ISSUE TITLE
3D Model - Rocket Tower

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/argame#36]
With the same platform, create the upper body of the turret. Reference to Steven's concept art. Keep towers under 1000 poly.

**Comment by BecBrock** [comment]
Low poly progress
![Image](https://user-images.githubusercontent.com/112132801/199150927-d3eb1c1a-a34b-4d8d-b011-e6c12dd0c75e.png)
![Image](https://user-images.githubusercontent.com/112132801/199150928-82867420-b855-4765-91c3-19cb5af1a08e.png)

**Comment by BecBrock** [comment]
Base for the guns

![Image](https://user-images.githubusercontent.com/112132801/200215654-b2aa2f91-dfe9-4965-840a-24040f7dca38.png)

**Comment by BecBrock** [comment]
![Image](https://user-images.githubusercontent.com/112132801/200223772-f1712898-6bbe-4742-a229-e64a7bec82a0.png)

**Comment by BecBrock** [comment]
![Image](https://user-images.githubusercontent.com/112132801/201942806-93e40897-56cf-4f32-bbdb-53d1af3b9401.png)



![Image](https://user-images.githubusercontent.com/112132801/201942926-5e9f63ff-683d-4415-9c47-41eb41513846.png)



![Image](https://user-images.githubusercontent.com/112132801/201942961-4805e8b7-2698-479b-b0ef-ecea1ca57b9a.png)
