### ISSUE TITLE
Greybox level 12 and 13

### ISSUE THREAD

**Issue by HschwandtHCC** [GAME-2332/argame#50]
Use your sketch and the initial greybox scene to create your own scenes for your assigned level and greybox your levels with the cubes. There is no need to change scale but make sure the cubes are positioned to line up with the unity grid. Place one of each tower in your scenes so that testing can begin ASAP.

**Comment by MaximusOctaviusss** [comment]
![Image](https://user-images.githubusercontent.com/112192552/200158400-20d0eb32-16ab-4b18-a9e8-bf49eb98067c.PNG)

Level 12

![Image](https://user-images.githubusercontent.com/112192552/200158404-55572bdf-7841-4548-b36a-782db0616175.PNG)

Level 13
