### ISSUE TITLE
Storyboard Trailer

### ISSUE THREAD

**Issue by Adicus-Alexander** [GAME-2332/argame#51]
Please create the storyboard for the trailer.
30 seconds to a minute in length.
Include space for gameplay footage
There is no explicit story for the game but feel free to come up with something simple if it helps.

**Comment by spiffyspades** [comment]
![GameTrailer_Storyboard](https://user-images.githubusercontent.com/112118309/201181573-5032aca5-d0b9-419d-b25b-a1b07dfc4f69.png)

**Comment by spiffyspades** [comment]
[https://drive.google.com/file/d/1l8VpnK_xgA28B9usmtSC6O8plGiU5Us6/view?usp=drivesdk](url)
