### ISSUE TITLE
2D Art Camp Environment Concepts

### ISSUE THREAD

**Issue by Adicus-Alexander** [GAME-2332/argame#6]
Create concept art and sketches of the military camp.  There is a board linked in the art document with references to temporary military bases and camps if you need it.

Include: 
-	A few different configurations of camp structures
-       Paths through the camp made with at least two different types of road
-	A few different angles of the camp 
-	Tents
-	Temporary structures
-	Temporary barricades
-       Fences/Walls

**Comment by ChrisGoodrum01** [comment]
![Concept Art](https://user-images.githubusercontent.com/112520495/197853664-c207b20e-c548-47b6-a721-e6e0dd7977d0.png)

**Comment by ChrisGoodrum01** [comment]
![Military Camp Ground](https://user-images.githubusercontent.com/112520495/197936976-e786be08-6a3d-435c-841d-e5a4ac7cf79f.png)
Making some more progress

**Comment by ChrisGoodrum01** [comment]
![Military Campground](https://user-images.githubusercontent.com/112520495/197937548-796ef138-ba27-435e-9016-284f5abf2964.png)

**Comment by ChrisGoodrum01** [comment]
![Concept Art Military](https://user-images.githubusercontent.com/112520495/198359411-a6528851-4417-49da-9398-7bbad7fcfccc.png)

**Comment by ChrisGoodrum01** [comment]
![Concept Art Military](https://user-images.githubusercontent.com/112520495/198359944-d084b483-418b-4e99-8891-1412dff28f88.png)
