### ISSUE TITLE
Tutorial Level & Level 1 Staging

### ISSUE THREAD

**Issue by HschwandtHCC** [GAME-2332/argame#67]
Please add textures such as grass for the plane, dirt for the enemy path, and concrete for tower placement cubes. Place props outside of the paths and add towers in place of the greybox towers that are in each scene so we can test with the actual towers instead. Keep everything where it is in the scene but just add the assets needed to make the scene look ready to play for public testing

**Comment by SBM382** [comment]
Tutorial Level
![Tutorial level_01](https://user-images.githubusercontent.com/70292179/202297714-43c00ed3-aedd-4537-8c6a-148306c7200c.png)
![Tutorial level_02](https://user-images.githubusercontent.com/70292179/202297726-e357a76f-8d6c-4799-a690-5fc68d851a55.png)
Level 1
![Level1_01](https://user-images.githubusercontent.com/70292179/202297743-ac288714-b493-4146-a95f-8f2dde9380bd.jpg)
![Level1_02](https://user-images.githubusercontent.com/70292179/202297753-fae44127-c2a8-4644-8be9-ec59e59febea.jpg)

**Comment by SBM382** [comment]
Level tutorial
![tutorial_1](https://user-images.githubusercontent.com/70292179/202595684-ec3ed590-853b-4e19-bdbf-5a8321529e4c.jpg)
![tutorial_2](https://user-images.githubusercontent.com/70292179/202595689-9acb4fe2-73e7-4eac-858e-a5706d26c38b.jpg)
Level 1
![Level_1_01](https://user-images.githubusercontent.com/70292179/202595763-ba5d2214-fc6a-490d-aad2-50e687a3a8ef.jpg)
![Level_1_02](https://user-images.githubusercontent.com/70292179/202595764-8fd51867-7860-4835-918e-945c8aaeb673.jpg)

The maps were re-adjusted.
