### ISSUE TITLE
2D Art Concept Enemy Design

### ISSUE THREAD

**Issue by Adicus-Alexander** [GAME-2332/argame#7]
Create concept art of the Enemy units.  Include a top-down view and at least one other angle for your designs.
Include:
-	Several troop designs
-	1-2 tower designs
-	Easily identifiable silhouettes
-	Easily identifiable uniforms
-	A few color schemes

**Comment by michaelHkitchener** [comment]
![qqP02EU01](https://user-images.githubusercontent.com/112128020/197845002-c5a99d96-fada-42be-a4ad-1dc2fe866ba3.jpg)
![qqP02EU02](https://user-images.githubusercontent.com/112128020/197845254-74826538-7ed9-4626-895a-a2c2f8241b92.jpg)
![qqP02enemyCon2](https://user-images.githubusercontent.com/112128020/197845533-32bf9ba5-48fa-4dcd-ac7d-858533ceef07.jpg)
![1CFAE692-13D9-44E9-830D-4F059706D3D2](https://user-images.githubusercontent.com/112128020/197845671-b9625b0d-1049-4ccf-a946-eece0a6db982.jpeg)
![5A906C65-445C-4D03-9418-18BD6401291E](https://user-images.githubusercontent.com/112128020/197845675-b27f6ccf-f9b5-4dd7-bcb9-ecc8711b6e3a.jpeg)
![457E5757-4D75-456E-8818-4CF4E665C735](https://user-images.githubusercontent.com/112128020/197845679-2fdea85b-15c4-479f-b07e-3d802b229879.jpeg)
![18E258EF-B271-452F-A978-2C2E320FC10A](https://user-images.githubusercontent.com/112128020/197845682-e54031c8-9c78-47aa-b6a4-ab576a7af21f.jpeg)

**Comment by michaelHkitchener** [comment]
Still working on towers, post again later today

**Comment by michaelHkitchener** [comment]
![Image](https://user-images.githubusercontent.com/112128020/198228596-4d83e6ab-0c2d-491f-aa1f-91772f7c38ac.jpg)

**Comment by michaelHkitchener** [comment]
![Image](https://user-images.githubusercontent.com/112128020/198283472-ce54b08b-2686-45aa-ba05-59c2b3a7de3f.jpg)

**Comment by michaelHkitchener** [comment]
lite trooper update

**Comment by michaelHkitchener** [comment]
![Image](https://user-images.githubusercontent.com/112128020/198362568-81776a07-5681-4257-a9ed-847de78e47e2.jpeg)

**Comment by michaelHkitchener** [comment]
Tower update

**Comment by michaelHkitchener** [comment]
![Image](https://user-images.githubusercontent.com/112128020/199308888-8f19929e-885c-46be-9d3c-7586a6047ba6.jpeg)
![Image](https://user-images.githubusercontent.com/112128020/199308889-da20bcf5-7262-4617-8267-cfd54289154c.jpeg)

**Comment by michaelHkitchener** [comment]
The last four images I’m ok with
