### ISSUE TITLE
2D Art Concept Player Design

### ISSUE THREAD

**Issue by Adicus-Alexander** [GAME-2332/argame#8]
Create concept art for the Player units. Include a top-down view and at least one other angle for your designs.
Include:
-	Several troop designs
-	1-2 Tower Designs
-	Easily identifiable silhouettes
-	Easily identifiable uniforms
-	A few color schemes

**Comment by Melissa971** [comment]
![Female Sniper Outfit Concept Color](https://user-images.githubusercontent.com/56281725/198354875-a91d3a4a-66f4-44d3-9d02-9e8e29d80e3e.png)
![Female Sniper Outfit Concept No Color](https://user-images.githubusercontent.com/56281725/198354877-1cc909b6-f1cf-4b4c-b7ac-eeb36c17e844.png)
![Heavy Arms Girl Outfit Concept Color](https://user-images.githubusercontent.com/56281725/198354878-30db8e0e-7fc1-401c-89c7-2f195baa1b1b.png)
![Heavy Arms Girl Outfit Concept No Color](https://user-images.githubusercontent.com/56281725/198354882-e9ec82c7-162f-4e0e-90a6-b67af3b64370.png)
![Male Outfit Concept Color](https://user-images.githubusercontent.com/56281725/198354884-bd9904ea-dfd7-4533-8d4f-be19dbd92aa0.png)
![Male Outfit Concept No Color](https://user-images.githubusercontent.com/56281725/198354887-86027359-79db-4955-b458-79a6f76a1839.png)




A few character designs, color isn't my strong suit so I included the non colored versions as well so it'll be more readable

**Comment by Melissa971** [comment]
![Base Concepts](https://user-images.githubusercontent.com/56281725/199656285-45e04635-d88b-44cb-81d2-04d96d1a4f62.png)
