### ISSUE TITLE
2D Art Concept Props

### ISSUE THREAD

**Issue by Adicus-Alexander** [GAME-2332/argame#9]
Design environmental props for the game. Include a top-down view and at least one other angle of each design. You may include additional props as you see fit.
This includes: 
-	Rocks
-	Trees 
-	Bushes
-	Barrels
-	Crates
-	Barricades
-	Barriers
-	Storage containers

**Comment by professaurChris** [comment]
This needs to be completed asap.

**Comment by spiffyspades** [comment]
![PropsConcepts_Barricades_1](https://user-images.githubusercontent.com/112118309/199236600-7e3da72c-4dfd-4c58-81e7-83dac14023a3.png)
![PropsConcepts_Enviormentthings_1](https://user-images.githubusercontent.com/112118309/199236603-b92c932d-8fc8-45b4-a976-a53c71b06b6e.png)
![PropsConcepts_Storage_1](https://user-images.githubusercontent.com/112118309/199236605-17eedcfb-7f8b-4980-9be2-176fe4585a1e.png)
